// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwZtVnkIjGsCPCJxMxI7IxppIs2UrQTqo',
    appId: '1:1042547238796:web:8a3ff8a4a6091470c298a9',
    messagingSenderId: '1042547238796',
    projectId: 'agrotech-cf790',
    authDomain: 'agrotech-cf790.firebaseapp.com',
    storageBucket: 'agrotech-cf790.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPUyzuE0vta6SAUrzjMofkvx_r8GYwlqQ',
    appId: '1:1042547238796:android:519e5451a51ae89fc298a9',
    messagingSenderId: '1042547238796',
    projectId: 'agrotech-cf790',
    storageBucket: 'agrotech-cf790.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd06UB8nxpomlVu30Rdbz4NDTEfetLyyE',
    appId: '1:1042547238796:ios:96a152e007eb24a2c298a9',
    messagingSenderId: '1042547238796',
    projectId: 'agrotech-cf790',
    storageBucket: 'agrotech-cf790.appspot.com',
    androidClientId: '1042547238796-o99003tbf7rm3gkqm56t4uoeiorui6i3.apps.googleusercontent.com',
    iosBundleId: 'com.cognizant.agrotech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd06UB8nxpomlVu30Rdbz4NDTEfetLyyE',
    appId: '1:1042547238796:ios:278f7ae1eeace973c298a9',
    messagingSenderId: '1042547238796',
    projectId: 'agrotech-cf790',
    storageBucket: 'agrotech-cf790.appspot.com',
    androidClientId: '1042547238796-o99003tbf7rm3gkqm56t4uoeiorui6i3.apps.googleusercontent.com',
    iosBundleId: 'com.example.agroTech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwZtVnkIjGsCPCJxMxI7IxppIs2UrQTqo',
    appId: '1:1042547238796:web:1819b97cfa4678d9c298a9',
    messagingSenderId: '1042547238796',
    projectId: 'agrotech-cf790',
    authDomain: 'agrotech-cf790.firebaseapp.com',
    storageBucket: 'agrotech-cf790.appspot.com',
  );

}